version: "3.8"
volumes:
  n8n:
  redis_data:
x-shared: &shared
  restart: always
  environment:
    # External Postgres Database
    DB_TYPE: postgresdb
    DB_POSTGRESDB_HOST: ${POSTGRES_HOST}
    DB_POSTGRESDB_PORT: ${POSTGRES_PORT}
    DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
    DB_POSTGRESDB_USER: ${POSTGRES_USER}
    DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

    # External Redis Cache
    QUEUE_BULL_REDIS_HOST: ${REDIS_HOST}
    QUEUE_BULL_REDIS_DB: ${REDIS_DB}
    QUEUE_BULL_REDIS_PORT: ${REDIS_PORT}
    QUEUE_BULL_REDIS_USERNAME: ${REDIS_USERNAME}
    QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
    #QUEUE_BULL_REDIS_TIMEOUT_THRESHOLD:
    #QUEUE_BULL_REDIS_CLUSTER_NODES:
    #QUEUE_BULL_REDIS_TLS:

    # Queue mode for scaling
    EXECUTIONS_MODE: queue
    QUEUE_HEALTH_CHECK_ACTIVE: "true"
    # Webhook API URLs
    WEBHOOK_TUNNEL_URL: https://${DOMAIN}
    WEBHOOK_URL: https://${DOMAIN}
    N8N_ENDPOINT_WEBHOOK: api
    N8N_ENDPOINT_WEBHOOK_TEST: api-test
    # N8N authentication
    N8N_BASIC_AUTH_ACTIVE: "true"
    N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
    N8N_BASIC_AUTH_PASSWORD: ${SOFTWARE_PASSWORD}
    N8N_HOST: ${DOMAIN}
    N8N_EMAIL_MODE: "smtp"
    N8N_SMTP_HOST: ${SMTP_HOST}
    N8N_SMTP_PORT: ${SMTP_PORT}
    N8N_SMTP_USER: " "
    N8N_SMTP_PASS: " "
    N8N_SMTP_SENDER: ${SMTP_FROM_EMAIL}
    N8N_SMTP_SSL: "false"
    NODE_TLS_REJECT_UNAUTHORIZED: 1
    EXECUTIONS_DATA_PRUNE: "true"
    EXECUTIONS_DATA_MAX_AGE: 336
    N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
  volumes:
    - ./n8n:/home/node/.n8n
services:
  n8n:
    <<: *shared
    # Path to dockerfile.'./' represents the current directory in which docker-compose.yml is present.
    build: ./
    image: repo/n8n:v1
    dns:
      - 8.8.8.8
    ports:
      - 172.17.0.1:5678:5678
  n8n-worker:
    <<: *shared
    image: repo/n8n:v1
    command: worker
    depends_on:
      - n8n
